const range = "A1,N1";
const tableName = "RegistrationTable";
const headers = [
  "name",
  "label.value",
  "placeholder",
  "fieldType",
  "description",
  "required",
  "minLength",
  "pattern",
  "constraintMessages.minLength",
  "constraintMessages.pattern",
  "enum",
  "enumNames",
  "rules.value",
  "events.click",
];

const body = [
  [
    "firstName",
    "First Name",
    "E.g. Buzz",
    "",
    "",
    "TRUE",
    "2",
    "",
    "First name must be at least two characters",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "lastName",
    "Last Name",
    "E.g. Ligthyear",
    "",
    "",
    "TRUE",
    "2",
    "",
    "Last name must be at least two characters",
    "",
    "",
    "",
    "",
    "",
  ],
  ["fullName", "Full Name", "", "", "", "", "", "", "", "", "", "", "firstName & ' ' & lastName", ""],
  [
    "email",
    "E-Mail",
    "E.g. buzz@nasa.gov",
    "email",
    "",
    "TRUE",
    "",
    "[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,}$",
    "",
    "Please enter valid email address",
    "",
    "",
    "",
    "",
  ],
  ["company", "Company Name", "E.g. Nasa", "", "", "TRUE", "", "", "", "", "", "", "", ""],
  [
    "company-size",
    "Company Size",
    "Select One",
    "select",
    "",
    "TRUE",
    "",
    "",
    "",
    "",
    "1-10, 11-50, 51-200, 201-500, 501-1000, 1001-5000, +5000",
    "1-10, 11-50, 51-200, 201-500, 501-1000, 1001-5000, +5000",
    "",
    "",
  ],
  [
    "phone",
    "Phone",
    "E.g. +1 555 555 5555",
    "string",
    "",
    "TRUE",
    "",
    "^(?!0+$)(+d{1,3}[- ]?)?(?!0+$)d{10}$",
    "",
    "Phone Number Should be 10 digit number with optional country code.",
    "",
    "",
    "",
    "",
  ],
  [
    "subscribe",
    "Subscribe to  blog and get the best in design thinking delivered biweekly.",
    "",
    "checkbox",
    "We need your phone number for the demo. We'll never use it for any other purposes.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  ["submit", "Let's chat", "", "button", "", "", "", "", "", "", "", "", "", "submitForm()"],
];
